/* automatically generated by rust-bindgen */

extern "C" {
    pub fn setSummand(summand: ::std::os::raw::c_int);
}
extern "C" {
    pub fn add(summand: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
